package com.fernandopaniagua.juliaset;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.SwingConstants;

/**
 * JFrame principal de la aplicación
 *  
 * @author Fernando Paniagua
 */
public class Frame extends javax.swing.JFrame {

    public static int anchoScreen;//Ancho del JFrame
    public static int altoScreen;//Alto del JFrame
    Panel panel = new Panel();//Panel de dibujo del fractal

    /**
     * Creates new form Ejecutador
     */
    public Frame() {
        initComponents();
        //Cálculo del tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        altoScreen = (int)(screenSize.getHeight()-jpControl.getHeight());
        //altoScreen=600;
        anchoScreen = (int)(altoScreen/0.75);
        //Asigna dimensiones, título y agrega panel
        this.setBounds(0, 0, anchoScreen, altoScreen + jpControl.getHeight());
        this.setTitle("Julia Set Generator - Fernando Paniagua (2017)");
        this.getContentPane().add(panel);
        //Carga del combobox
        jcbPredefinidos.addItem("0,0");
        jcbPredefinidos.addItem("0,0.8");
        jcbPredefinidos.addItem("0.25,0");
        jcbPredefinidos.addItem("0.275,0");
        jcbPredefinidos.addItem("0.279,0");
        jcbPredefinidos.addItem("0.285,0.535");
        jcbPredefinidos.addItem("0.285,-0.01");
        jcbPredefinidos.addItem("-0.125,0.750");
        jcbPredefinidos.addItem("-0.500,0.563");
        jcbPredefinidos.addItem("-0.75,0");
        jcbPredefinidos.addItem("-0.8,0");
        jcbPredefinidos.addItem("-0.8,-0.25");
        jcbPredefinidos.addItem("-1.375,0.02");
        jcbPredefinidos.addItem("-1.312,0");
        //Alinea los JTextField
        jtfCReal.setHorizontalAlignment(SwingConstants.RIGHT);
        jtfCImaginaria.setHorizontalAlignment(SwingConstants.RIGHT);
        //Genera el primer fractal (por defecto)
        generar();
    }

    /**
     * Inicia el proceso de generación del fractal
     */
    private void generar(){
        String cReal=jtfCReal.getText();
        String cImaginaria=jtfCImaginaria.getText();
        String sColor=(String) jcbColor.getSelectedItem();
        String sIncremento=(String) jcbBrillo.getSelectedItem();    
    
        Color color;
        int incremento;
        if (sColor.equals("Rojo")) {
            color = Color.RED;
        } else if (sColor.equals("Verde")) {
            color = Color.GREEN;
        } else {
            color = Color.BLUE;
        }
        incremento = Integer.parseInt(sIncremento);
        panel.generar(cReal, cImaginaria, color, incremento);
        panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpControl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbPredefinidos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfCReal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCImaginaria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbBrillo = new javax.swing.JComboBox<>();
        jbGenerar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel3.setText("c");
        jpControl.add(jLabel3);

        jcbPredefinidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPredefinidosActionPerformed(evt);
            }
        });
        jpControl.add(jcbPredefinidos);

        jLabel1.setText("c (real)");
        jpControl.add(jLabel1);

        jtfCReal.setColumns(5);
        jtfCReal.setText("0.285");
        jtfCReal.setMinimumSize(new java.awt.Dimension(800, 600));
        jpControl.add(jtfCReal);

        jLabel2.setText("c (imaginaria)");
        jpControl.add(jLabel2);

        jtfCImaginaria.setColumns(5);
        jtfCImaginaria.setText("-0.01");
        jpControl.add(jtfCImaginaria);

        jLabel4.setText("Color");
        jpControl.add(jLabel4);

        jcbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Verde", "Azul" }));
        jpControl.add(jcbColor);

        jLabel5.setText("Brillo");
        jpControl.add(jLabel5);

        jcbBrillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "20", "30", "40", "50" }));
        jcbBrillo.setSelectedIndex(4);
        jpControl.add(jcbBrillo);

        jbGenerar.setText("Generar");
        jbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarActionPerformed(evt);
            }
        });
        jpControl.add(jbGenerar);

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jpControl.add(jbGuardar);

        getContentPane().add(jpControl, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarActionPerformed
        // TODO add your handling code here:
        generar();
    }//GEN-LAST:event_jbGenerarActionPerformed

    private void jcbPredefinidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPredefinidosActionPerformed
        // TODO add your handling code here:
        String c = (String) jcbPredefinidos.getSelectedItem();
        jtfCReal.setText(c.substring(0, c.indexOf(',')));
        jtfCImaginaria.setText(c.substring(c.indexOf(',') + 1, c.length()));
    }//GEN-LAST:event_jcbPredefinidosActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        panel.guardar();
    }//GEN-LAST:event_jbGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbGenerar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbBrillo;
    private javax.swing.JComboBox<String> jcbColor;
    private javax.swing.JComboBox<String> jcbPredefinidos;
    private javax.swing.JPanel jpControl;
    private javax.swing.JTextField jtfCImaginaria;
    private javax.swing.JTextField jtfCReal;
    // End of variables declaration//GEN-END:variables
}
